### ISSUE TITLE
Xcode 7 compile error undeclared type Sequence?

### ISSUE THREAD

**Issue by justdan0227** [danthorpe/ValueCoding#25]
When attempting to run this on an Xcode7 project I'm getting "Use of undeclared type Sequence" on 

public extension Sequence where Iterator.Element: CodingProtocol {

line 55 ?

**Comment by danthorpe** [comment]
Hello @justdan0227 - you are using version 2, which is for Swift 3 & Xcode 8. If you are still using Xcode 7 (and therefore Swift 2.2) you will need to pin your version to 1.4.0. See [Releases](https://github.com/danthorpe/ValueCoding/releases) for more info.

**Comment by justdan0227** [comment]
oh sorry.. missed that.   Is there a pod command to get 1.4.0?

**Comment by danthorpe** [comment]
put this in your Podfile:

```ruby
pod 'ValueCoding', '1.4.0'
```

See: [CocoaPods guides/documentation](https://guides.cocoapods.org/using/the-podfile.html#specifying-pod-versions).

**Comment by justdan0227** [comment]
So using 1.4.0 now,  however getting "Header 'stdatomic.h' not found" ?

**Comment by danthorpe** [comment]
Well, ValueCoding is a single Swift file with zero dependencies.

 I'm not sure I can really provide much more info than Google will, and this seems very likely to be unrelated to ValueCoding. Try a clean build?
