### ISSUE TITLE
Add tvOS to pod spec?

### ISSUE THREAD

**Issue by rjgdesign** [danthorpe/ValueCoding#4]
Add tvOS to pod spec?

**Comment by danthorpe** [comment]
Yep - will do.

**Comment by rjgdesign** [comment]
Sweet - can't wait. Using the library today, great job!

**Comment by danthorpe** [comment]
No problems - it's pretty simple - developed for [YapDatabaseExtensions](https://github.com/danthorpe/YapDatabaseExtensions) see [this post](http://danthorpe.me/posts/yapdatabaseextensions-two--the-swiftening.html) for a bit more info about ValueCoding...

Will get to this in the hour.

**Comment by danthorpe** [comment]
Okay - done in version 1.1.0. Let me know if you have any problems!
